---
# This playbook installs nginx

- name: install nginx
  apt: name=nginx state=present
  tags: nginx

- template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: start nginx kitchen docker
  shell: /usr/sbin/nginx &
  when: ( containerised and kitchen )
