---
# This playbook installs nginx

- name: install nginx
  apt: name=nginx state=present
  tags: nginx
  when: ansible_os_family == "Debian"

- name: Add epel repository
  yum: name=epel-release
  when: ansible_os_family == "RedHat"

- name: install nginx
  yum: name=nginx state=present
  tags: nginx
  when: ansible_os_family == "RedHat"

- template:
    src: "nginx-{{ ansible_os_family }}.conf.j2"
    dest: /etc/nginx/nginx.conf

- service:
    name: nginx
    state: restarted
  when: ( not containerised )

- name: start nginx kitchen docker
  shell: /usr/sbin/nginx &
  when: ( containerised and kitchen )
