---
driver:
  name: docker
#  forward: 8080
#  network:
#  - [ "forwarded_port", {guest: 8080, host: 8080} ]
#  run_command: "/usr/sbin/sshd -D -o UseDNS=no -o UsePAM=no -o PasswordAuthentication=yes -o UsePrivilegeSeparation=no -o PidFile=/tmp/sshd.pid"

provisioner:
  # use an ansible playbook to provision our server
  name: ansible_playbook
  # name of the host
  hosts: test-kitchen
  playbook: main.yml
  # list of ansible galaxy requirements from the roles meta/main.yml
  # requirements_path: dependencies.yml
  extra_vars:
    containerised: true

verifier:
  name: inspec

transport:
  max_ssh_sessions: 6

platforms:
  - name: ubuntu-16.04
#    driver_config:
#      forward:
#      - 8080:8080

suites:
  # suites found at /test/integration/$test-name
  - name: default
